### ISSUE TITLE
issue trying to run from source code

### ISSUE THREAD

**Issue by Jmanugget** [doublespeakgames/gridland#62]
For a dark room I've downloaded the source code and ran index.html, it worked flawlessly but when i try to do the same for gridland it gets stuck at that loading screen before you can click on new game.

**Comment by Continuities** [comment]
Likely due to asset loading failures from localhost. Check your browser
console for errors.

**Comment by Jmanugget** [comment]
Darn I can't open chrome console on these school chromebooks.

**Comment by Continuities** [comment]
Really? Right clicking on the page and choosing 'Inspect' doesn't work?

**Comment by Jmanugget** [comment]
Ok I tried it on a school pc which I can open the console. and this is what i got...Failed to load resource: the server responded with a status of 403 (Forbidden)
icons.png Failed to load resource: the server responded with a status of 403 (Forbidden)
buildings.png Failed to load resource: the server responded with a status of 403 (Forbidden)
monsters.png Failed to load resource: the server responded with a status of 403 (Forbidden)
dragonsprite.png Failed to load resource: the server responded with a status of 403 (Forbidden)
tiles.png Failed to load resource: the server responded with a status of 403 (Forbidden)
icons.png Failed to load resource: the server responded with a status of 403 (Forbidden)
tiles.png Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by Continuities** [comment]
Aha, it looks like I hardcoded paths to the official doublespeak media
server for the audio (and maybe the images too). You'll have to fix that
path (or remove the audio) to make it work locally.

**Comment by Jmanugget** [comment]
How do I go about fixing this/ where is the file I need to edit and what do I change in it and to what.

**Comment by Continuities** [comment]
I'm *guessing* that it's hanging when trying to initialize the audio.
Engine.js initializes all its required modules on line 207, and GameAudio
is one of them. You should be able to prevent it from doing that (you'll
get no audio), or check the init function in audio.js and try to make it
work. The specifics are left as an exercise to the reader! If you wanna
play games in class, you're going to have to work for it =)

**Comment by Jmanugget** [comment]
Im trying the route of changing the cdn path to gridland-master folder but i don't know how to make it universal for any machine.

**Comment by Jmanugget** [comment]
Not to play games in class but as a side project for my coding class. I'm trying to learn a little javascript what a better way than to go knees deep in the code of one the best games ever made. Also the cdn thing didn't work as some sort of security protocol block executing the files straight from the hard drive? is there any way to add it to the sources that it uses. I looked at the sources page in chrome dev tools and the img and audio folders aren't included.

**Comment by Continuities** [comment]
Gridland uses XmlHttpRequests to load audio assets, which don't work
against file:// targets. You'll need to set up a simple web server on your
machine (it doesn't have to be accessible to the internet, though) and host
Gridland from there instead.

**Comment by Jmanugget** [comment]
Ok we haven't gotten into XmlHttpRequests and webservers so how do I setup a little webserver.

**Comment by Continuities** [comment]
I don't have much experience with Chromebooks, but this looks promising?
https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en

**Comment by Jmanugget** [comment]
So I cloned the www folder into a new repo here https://github.com/Jmanugget/grid  and I have it set to use github sites which you can check out here https://jmanugget.github.io/grid/ but I am still having an error so how do I fix it. I got the error of it not loading the google scrpits because they were http and the site is https so i went and changed those to https but now I'm on a chromebook so I don't know what the new error is.

**Comment by Jmanugget** [comment]
So I'm at home now and using my pc I've found and resolved all the errors, the chrome console is blank yet it still won't load. It is still at the same point it always was, in other words I'm stuck.

**Comment by Jmanugget** [comment]
So what could possibly make it not load?

**Comment by Jmanugget** [comment]
Just changed some settings. Specifically logxmlhttps requests to true and I got this:09:44:53.647 jquery.min.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:5
(anonymous) @ jquery.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
on @ jquery.min.js:5
init @ engine.js:158
(anonymous) @ main.js:4
execCb @ require.js:29
check @ require.js:18
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
enable @ require.js:23
init @ require.js:17
D @ require.js:14
completeLoad @ require.js:28
onScriptLoad @ require.js:29
09:44:53.648 jquery.min.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:5
(anonymous) @ jquery.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
on @ jquery.min.js:5
init @ engine.js:167
(anonymous) @ main.js:4
execCb @ require.js:29
check @ require.js:18
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
enable @ require.js:23
init @ require.js:17
D @ require.js:14
completeLoad @ require.js:28
onScriptLoad @ require.js:29
09:44:53.709 jquery.min.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:5
(anonymous) @ jquery.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
on @ jquery.min.js:5
init @ audio.js:108
init @ graphics.js:473
initModule @ engine.js:33
initModule @ engine.js:38
initModule @ engine.js:38
initModule @ engine.js:38
initModule @ engine.js:38
initializeModules @ engine.js:42
init @ engine.js:207
(anonymous) @ main.js:4
execCb @ require.js:29
check @ require.js:18
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
enable @ require.js:23
init @ require.js:17
D @ require.js:14
completeLoad @ require.js:28
onScriptLoad @ require.js:29
09:44:53.710 jquery.min.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:5
(anonymous) @ jquery.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
on @ jquery.min.js:5
init @ audio.js:109
init @ graphics.js:473
initModule @ engine.js:33
initModule @ engine.js:38
initModule @ engine.js:38
initModule @ engine.js:38
initModule @ engine.js:38
initializeModules @ engine.js:42
init @ engine.js:207
(anonymous) @ main.js:4
execCb @ require.js:29
check @ require.js:18
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
enable @ require.js:23
init @ require.js:17
D @ require.js:14
completeLoad @ require.js:28
onScriptLoad @ require.js:29
09:44:53.710 jquery.min.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:5
(anonymous) @ jquery.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
on @ jquery.min.js:5
init @ audio.js:110
init @ graphics.js:473
initModule @ engine.js:33
initModule @ engine.js:38
initModule @ engine.js:38
initModule @ engine.js:38
initModule @ engine.js:38
initializeModules @ engine.js:42
init @ engine.js:207
(anonymous) @ main.js:4
execCb @ require.js:29
check @ require.js:18
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
enable @ require.js:23
init @ require.js:17
D @ require.js:14
completeLoad @ require.js:28
onScriptLoad @ require.js:29
09:44:53.711 jquery.min.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:5
(anonymous) @ jquery.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
on @ jquery.min.js:5
attachHandler @ gameboard.js:307
attachHandler @ graphics.js:493
init @ engine.js:231
(anonymous) @ main.js:4
execCb @ require.js:29
check @ require.js:18
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
enable @ require.js:23
init @ require.js:17
D @ require.js:14
completeLoad @ require.js:28
onScriptLoad @ require.js:29
09:44:53.712 jquery.min.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:5
(anonymous) @ jquery.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
on @ jquery.min.js:5
attachHandler @ gameboard.js:307
attachHandler @ graphics.js:493
init @ engine.js:250
(anonymous) @ main.js:4
execCb @ require.js:29
check @ require.js:18
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
enable @ require.js:23
init @ require.js:17
D @ require.js:14
completeLoad @ require.js:28
onScriptLoad @ require.js:29
09:44:53.713 jquery.min.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:5
(anonymous) @ jquery.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
on @ jquery.min.js:5
attachHandler @ world.js:21
attachHandler @ graphics.js:493
init @ engine.js:292
(anonymous) @ main.js:4
execCb @ require.js:29
check @ require.js:18
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
(anonymous) @ require.js:23
(anonymous) @ require.js:8
(anonymous) @ require.js:23
y @ require.js:7
emit @ require.js:23
check @ require.js:19
enable @ require.js:23
init @ require.js:17
D @ require.js:14
completeLoad @ require.js:28
onScriptLoad @ require.js:29

**Comment by Continuities** [comment]
Those don't look like fatal errors to me, just some linting stuff.

**Comment by Jmanugget** [comment]
The red square is still in the top left corner and the title doesn't appear above the loading wheel and it still wont bring up the option to start new game.

**Comment by Jmanugget** [comment]
I little more tweaking and I got it to work. Thank you for your help

**Comment by Continuities** [comment]
Glad to hear it! Happy hacking.

**Comment by simonsnow** [comment]
Jmanugget, any chance you want to share what you did in case anybody wants to dive in and hack around in there too? :)

**Comment by Jmanugget** [comment]
So the only issue is that you cannot play it offline. ( At least not with this method.) Which is kind of unfortunate because I love to run ADR from source code off my thumbdrive when there is no internet. So first off you need to have a github account and you need to make a new repo. For the code you're going to want to download this repo and then push ONLY the contents of the www folder to your new repo. !!! Change the readme file so that it displays that it is not your own work because obviously it is imported from doublespeakgames, they put their time into this game so they get the credit !!! once that's taken care of go into repo settings and set github pages to master branch. (pick any theme it doesn't matter) now go to website it should be yourusernamehere.github.io/reponame and copy the address. Now that the address is in your clipboard go into /js/app/graphics/sprites.js and change "CDN_PATH" to the web address you copied. Do the same thing to /js/app/audio/audio.js . Now here's the "fun" part. go into /css/main.css and edit the file. Now use the edit systems find text feature to find all "https" change EVERY address to your web page address (It will take awhile) You're almost done. Go to /js/app.js and change any http to https. You should be done by now if an issue persits ask on this issue and I will probaly respond. Good Luck!

**Comment by simonsnow** [comment]
Thanks for the very detailed instructions! Once I get digging I'm sure I'll
have no trouble. I was just looking for the files that I should be looking
in to get it working. Since what it seems like you are doing is just
changing hard coded paths to things, why not have a local server set up
along with an edited hosts file to trick things into working locally? I
know you mentioned you were using a chromebook so I don't know the
viability of this option on there as I've never used one.

--
Cheers,
Simon

**Comment by Jmanugget** [comment]
I don't know how to do that on any machine unfortunatly.

**Comment by simonsnow** [comment]
I got curious and did a bit of googling ;)

Your best option on a chromebook is to use this utility DNS name
localtest.me (http://readme.localtest.me/). How cool! I love these utility
DNS setups. This would be useful on any machine really.
anything.localtest.me will simply point to 127.0.0.1. So you tell your
local web server that it's to serve files under the host name
anything.localtest.me, then just fire up that URL in your browser and it
will point to your local webserver set up for that address! Neat.

So as long as you have a local web server and all the files in the right
places you should be able to replace the URLS in the configs with
anything.localtest.me and I would think it should work as long as SSL isn't
required anywhere.

Oh I found this too if you want to really get into web development on a
chromebook:
https://medium.com/@martinmalinda/ultimate-guide-for-web-development-on-chromebook-part-1-crouton-2ec2e6bb2a2d


--
Cheers,
Simon

**Comment by CarlosRoldanx** [comment]
Hey @Jmanugget What about if I do not want to use this in GitHub Pages, just locally? I have mapped all the css to the local files but... What about the CDN PATH?

I have tried:

1. 	var CDN_PATH = "/gridland/www/index.html";

2.  	var CDN_PATH = "C:\Users\username\Desktop\folder\gridland\www\index.html";


And the console says it can not GET those files...
